const $=id=>document.getElementById(id);
const money=v=>v==null?'--':'$'+Number(v).toFixed(2);
const moneyOrNote=(v,note)=>v==null?(note||'--'):'$'+Number(v).toFixed(2);
const num=(v,d=2)=>v==null?'--':Number(v).toFixed(d);
const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const ts=ms=>ms?new Date(Number(ms)).toLocaleString('zh-CN',{hour12:false}):'--';
const pct=v=>v==null?'--':(Number(v)*100).toFixed(1)+'%';
const px=v=>v==null?'--':Number(v).toFixed(2);
async function api(p,opt){const r=await fetch(p,{cache:'no-store',...(opt||{})});return await r.json()}
function qs(box){return [...document.querySelectorAll(`#${box} [name]`)].map(i=>`${encodeURIComponent(i.name)}=${encodeURIComponent(i.value||'')}`).join('&')}
function clsPnl(v){return Number(v||0)>=0?'ok':'bad'}
function orderStatusZh(x){const k=String(x.kind||x.status||x.state||'').toLowerCase();if(k.includes('settled_win'))return '<span class="ok">已赢</span>';if(k.includes('settled_loss'))return '<span class="bad">已输</span>';if(k.includes('settled'))return x.won?'<span class="ok">已赢</span>':'<span class="bad">已输</span>';if(k.includes('filled'))return '<span class="ok">已成交</span>';if(k.includes('submitted'))return '<span class="warn">已提交</span>';if(k.includes('failed')||k.includes('rejected')||k.includes('timeout'))return '<span class="bad">失败</span>';if(k.includes('skip'))return '<span class="unknown">跳过</span>';return esc(x.status||x.state||x.kind||'--')}
function wonText(v){return v===true?'<span class="ok">赢</span>':v===false?'<span class="bad">输</span>':'<span class="unknown">--</span>'}
function rowProb(x){const d=String(x.direction||x.dir||'').toLowerCase();const p=d==='up'?x.p_up:d==='down'?x.p_down:(x.p_up??x.p_down);return p==null?'--':pct(p)}
function shortOrder(x){return esc(String(x.exchange_order_id||x.client_order_id||'').slice(-18)||'--')}
function rows(id,a,f,col=9){$(id).innerHTML=a&&a.length?a.map(f).join(''):`<tr><td colspan="${col}" class="muted">暂无数据</td></tr>`}
function setText(id,v){const e=$(id);if(e)e.textContent=v}
async function copyText(text,msgId){try{await navigator.clipboard.writeText(text);setText(msgId,'已复制 '+new Date().toLocaleTimeString('zh-CN',{hour12:false}))}catch(e){setText(msgId,'复制失败，请手动选择文本')}}
function orderAuditRows(){return (lastRealOrders||[]).map(x=>({time:ts(x.ts_ms),kind:x.kind||'',window_id:x.window_id||'',direction:(x.direction||x.side||'').toUpperCase(),amount:x.size_usdc??x.amount??'',class:x.error_class||'',error:x.error||x.last_error||x.state||x.status||'',order:String(x.client_order_id||x.exchange_order_id||'')}))}
function copyRealOrdersTSV(){const cols=['time','kind','window_id','direction','amount','class','error','order'];const rows=[cols.join('\t'),...orderAuditRows().map(r=>cols.map(c=>String(r[c]??'').replace(/[\t\r\n]+/g,' ')).join('\t'))];copyText(rows.join('\n'),'real-orders-copy-msg')}
function copyRealOrdersJSON(){copyText(JSON.stringify(lastRealOrders||[],null,2),'real-orders-copy-msg')}
function stat(prefix,s){setText(`${prefix}-count`,s.count??0);setText(`${prefix}-wr`,pct(s.win_rate));setText(`${prefix}-pnl`,money(s.total_pnl));setText(`${prefix}-avgpnl`,money(s.avg_pnl));setText(`${prefix}-avgamt`,money(s.avg_amount))}
let liveClock={t:null,at:0};
let lastRealOrders=[];
let lastRealOrderClasses=[];
function tickTime(){if(liveClock.t==null){setText('m-time','--');return}const left=Math.max(0,liveClock.t-(Date.now()-liveClock.at)/1000);setText('m-time',Math.round(left)+'s')}
function statusZh(s){return s==='pass'?'通过':s==='fail'?'未通过':s==='warn'?'注意':'待判断'}
function actionZh(s){return ({submitted:'已提交/已尝试提交',already_attempted_this_condition:'本合约已尝试过，等待下一窗口',waiting_minute3_close:'等待第 3 分钟收盘确认',no_best_ask:'盘口没有可买价格',skip_low_confidence:'方向置信度不足',skip_no_edge:'EV/edge 不足',order_submitted:'订单已提交',order_filled:'订单已成交'}[String(s||'')])||String(s||'--')}
function sideZh(s){const x=String(s||'').toLowerCase();return x==='up'?'上涨 UP':x==='down'?'下跌 DOWN':String(s||'未确定')}
function orderBox(o){return o?`<div class="notice"><b>当前窗口真实 FOK 已成交</b><br>方向：<b>${esc((o.direction||o.side||'').toUpperCase())}</b> ｜ 金额：<b>${money(o.size_usdc||o.amount)}</b> ｜ 价格：<b>${num(o.price,4)}</b><br><span class="muted">订单：${esc(String(o.exchange_order_id||o.client_order_id||'').slice(-32))} ｜ 时间：${ts(o.ts_ms)}</span></div>`:''}
function sideMarket(dec,side){const isUp=side==='up', active=(dec.evaluated_direction||dec.best_dir)===side;const prob=isUp?dec.p_up:dec.p_down;const ask=isUp?dec.ask_up:dec.ask_down;const bid=isUp?dec.bid_up:dec.bid_down;const edge=active?dec.best_ev:null;const edgeCls=edge==null?'unknown':edge>=0.08?'edgegood':'edgebad';const title=isUp?'UP 上涨':'DOWN 下跌';return `<div class="sidebox ${active?'active':''}"><h3><span>${title}</span><span>${active?'当前选择':''}</span></h3><div class="bigprob">${pct(prob)}</div><div class="kv"><span>模型概率</span><b>${pct(prob)}</b><span>最佳卖价</span><b>${px(ask)}</b><span>最佳买价</span><b>${px(bid)}</b><span>机会差值</span><b class="${edgeCls}">${edge==null?'--':num(edge,4)}</b></div></div>`}
function marketPanel(dec){const updated=dec.server_ts_ms?new Date(dec.server_ts_ms).toLocaleTimeString('zh-CN',{hour12:false}):'--';return `<div class="marketbox">${sideMarket(dec,'up')}${sideMarket(dec,'down')}</div><div class="fresh">当前策略：${esc(dec.decision_mode||'实盘三位序列策略')} ｜ 序列：${esc(dec.seq_display||dec.seq||'--')} ｜ 更新时间：${updated} ｜ Phase0 EV>0.30，Phase1 EV>0.15，Phase2/3/4 净EV>0</div>`}
function drawBalanceChart(items){const svg=$('balance-chart');if(!svg)return;const w=520,h=240,p=28;svg.innerHTML='';if(!items||items.length===0){svg.innerHTML=`<text x="260" y="120" fill="#8ea0b6" text-anchor="middle">暂无余额历史，等待自动记录</text>`;return}const xs=items.map(x=>Number(x.ts_ms)),ys=items.map(x=>Number(x.balance_usdc));const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const yPad=Math.max(0.01,(maxY-minY)*0.15);const lo=minY-yPad,hi=maxY+yPad;const sx=x=>p+(maxX===minX?0.5:(x-minX)/(maxX-minX))*(w-p*2);const sy=y=>h-p-(hi===lo?0.5:(y-lo)/(hi-lo))*(h-p*2);let grid='';for(let i=0;i<4;i++){const y=p+i*(h-p*2)/3;grid+=`<line x1="${p}" y1="${y}" x2="${w-p}" y2="${y}" stroke="#263244" stroke-width="1"/><text x="4" y="${y+4}" fill="#8ea0b6" font-size="11">${(hi-(hi-lo)*i/3).toFixed(2)}</text>`}const d=items.map((x,i)=>(i?'L':'M')+sx(Number(x.ts_ms)).toFixed(1)+' '+sy(Number(x.balance_usdc)).toFixed(1)).join(' ');const last=items[items.length-1];svg.innerHTML=grid+`<path d="${d}" fill="none" stroke="#38d47a" stroke-width="3"/><circle cx="${sx(Number(last.ts_ms))}" cy="${sy(Number(last.balance_usdc))}" r="4" fill="#38d47a"/><text x="${w-p}" y="${p-8}" fill="#e5edf7" text-anchor="end" font-size="12">$${Number(last.balance_usdc).toFixed(2)}</text>`}
async function loadBalanceChart(){const range=$('balance-range')?.value||'1h';const j=await api('/api/real/balance_history?range='+encodeURIComponent(range));drawBalanceChart(j.items||[]);setText('bal-latest',money(j.latest));const d=Number(j.delta||0);const el=$('bal-delta');if(el){el.textContent=(d>=0?'+':'')+'$'+d.toFixed(4);el.className=d>=0?'ok':'bad'}setText('bal-count',`${j.count??0} / ${j.raw_count??0}`);setText('bal-source',`真实 Polymarket 账户链上余额 ｜ 范围：${range} ｜ ${j.count_note||'数据点为余额记录'}`)}
function conds(id,a){$(id).innerHTML=(a||[]).map(x=>`<div class="cond"><b>${esc(x.label)}</b><span class="${esc(x.status)}">${statusZh(x.status)}</span><span>${esc(x.key==='stage'?actionZh(x.text):x.text)}</span></div>`).join('')||'<div class="muted">暂无条件数据</div>'}
function phaseBoxes(dec){const boxes=dec.phase_boxes||[];if(!boxes.length){conds('real-conds',dec.real?.conditions||[]);return}const html=boxes.map(b=>{const state=b.state||'waiting';const cls=state==='current'?'active':state==='cleared'?'cleared':'waiting';const condHtml=(b.conditions||[]).length?(b.conditions||[]).map(x=>`<div class="phase-cond"><b>${esc(x.label)}</b><span class="${esc(x.status)}">${statusZh(x.status)}</span><small>${esc(x.text)}</small></div>`).join(''):`<div class="phase-empty">${esc(b.note||'等待')}</div>`;return `<div class="phasebox ${cls}"><div class="phase-head"><b>阶段 ${esc(b.phase)}</b><span>${esc(b.title||'')}</span></div><div class="phase-state">${esc(b.summary||'')}</div>${condHtml}</div>`}).join('');$('real-conds').innerHTML=`<div class="phasegrid">${html}</div>`}
async function loadLive(){
  const [sum,cw,dec,ver,st]=await Promise.all([api('/api/summary'),api('/api/current_window'),api('/api/current_decision'),api('/api/version'),api('/api/strategy/status')]);
  $('health').textContent='正常 '+new Date().toLocaleTimeString('zh-CN',{hour12:false});$('health').className='pill ok';
  $('st-run').textContent=st.running?'运行中':'已暂停';$('st-run').className=st.running?'ok':'bad';$('st-pid').textContent='PID '+(st.pid||'--');$('strategy-cmd').textContent=st.command||'--';$('btn-start').disabled=!!st.running;$('btn-stop').disabled=!st.running;
  $('m-real').textContent=moneyOrNote(sum.real_balance_usdc,'查询中/暂无');$('m-shadow').textContent=moneyOrNote(sum.shadow_equity_usdc,sum.shadow_equity_note||'无影子账户数据');$('m-window').textContent=dec.window_label||cw.window_label||'--';$('m-wid').textContent=dec.window_id||cw.window_id||'--';$('m-seq').textContent=dec.seq_display||dec.seq||dec.prefix||cw.seq||cw.prefix||'--';liveClock={t:dec.T_remaining,at:Date.now()};tickTime();$('m-ver').textContent=String(ver.deployed||ver.commit||'unknown').slice(0,12);
  $('real-reason').innerHTML=`当前结论：${esc(actionZh(dec.real?.reason||dec.real?.status))}`;$('real-dirbox').innerHTML=marketPanel(dec);$('real-fillbox').innerHTML=orderBox(dec.real?.filled_order);phaseBoxes(dec);await loadBalanceChart();

}
async function controlStrategy(action){const msg=$('strategy-msg');$('btn-start').disabled=true;$('btn-stop').disabled=true;msg.textContent=action==='start'?'正在启动...':'正在暂停...';try{const j=await api('/api/strategy/'+action,{method:'POST'});msg.textContent=j.ok?(action==='start'?'已启动/启动请求完成':'已暂停/暂停请求完成'):'失败：'+(j.error||j.reason||'unknown');await loadLive()}catch(e){msg.textContent='失败：'+e}}
async function loadReal(){
  const [r,o]=await Promise.all([api('/api/real/results?limit=20&'+qs('real-filters')),api('/api/real/orders?limit=20&'+qs('real-filters'))]);const s=r.stats||{};stat('real',s);$('real-bal').textContent=money(s.real_balance_usdc);$('real-coverage').textContent=pct(s.coverage_rate);$('real-coverage-sub').textContent=`${s.coverage_windows??0}/${s.coverage_total_windows??0} 个5分钟窗口`;
  rows('real-results',r.items,x=>`<tr><td><div>${ts(x.ts_ms)}</div><div class="mono muted">${esc(x.window_id)}</div></td><td class="mono">${esc(x.seq||'')}</td><td>${esc((x.direction||x.dir||'').toUpperCase())}</td><td>${orderStatusZh(x)}</td><td class="right">${money(x.amount||x.fill_amt||x.size_usdc)}</td><td class="right">${num(x.price,4)}</td><td class="right">${rowProb(x)}</td><td class="mono" title="${esc(x.exchange_order_id||x.client_order_id||'')}">${shortOrder(x)}</td><td class="right ${clsPnl(x.pnl)}">${x.pnl==null?wonText(x.won):money(x.pnl)+' '+wonText(x.won)}</td></tr>`,9);
  lastRealOrders=o.items||[];lastRealOrderClasses=o.error_classes||[];setText('real-orders-classes','失败分类：'+(lastRealOrderClasses.length?lastRealOrderClasses.map(x=>`${x[0]}=${x[1]}`).join('，'):'--'));
  rows('real-orders',o.items,x=>`<tr><td>${ts(x.ts_ms)}</td><td>${esc(x.kind)}</td><td class="mono">${esc(x.window_id||'')}</td><td>${esc((x.direction||x.side||'').toUpperCase())}</td><td>${money(x.size_usdc||x.amount)}</td><td>${esc(x.error_class||'')}</td><td>${esc(x.error||x.last_error||x.state||x.status||'')}</td><td class="mono">${esc(String(x.client_order_id||x.exchange_order_id||'').slice(-28))}</td></tr>`,8);
}
async function loadShadow(){
  const [r,o]=await Promise.all([api('/api/shadow/results?limit=20&'+qs('shadow-filters')),api('/api/shadow/orders?limit=20&'+qs('shadow-filters'))]);const s=r.stats||{};$('shadow-count').textContent=s.count??0;$('shadow-wr2').textContent=pct(s.win_rate);$('shadow-pnl').textContent=money(s.total_pnl);$('shadow-avgpnl').textContent=money(s.avg_pnl);$('shadow-avgamt').textContent=money(s.avg_amount);$('shadow-bal').textContent=money(s.shadow_equity_usdc);
  rows('shadow-results',r.items,x=>`<tr><td><div>${ts(x.ts_ms)}</div><div class="mono muted">${esc(x.window_id)}</div></td><td class="mono">${esc(x.seq||'')}</td><td>${esc((x.direction||x.dir||'').toUpperCase())}</td><td class="right">${money(x.amount||x.fill_amt)}</td><td class="right ${clsPnl(x.pnl)}">${money(x.pnl)}</td><td>${wonText(x.won)}</td><td class="right sim">${money(x.equity)}</td></tr>`,7);
  rows('shadow-orders',o.items,x=>`<tr><td><div>${ts(x.ts_ms)}</div><div class="mono muted">${esc(x.window_id)}</div></td><td class="mono">${esc(x.seq||x.trigger_pattern||'')}</td><td>${esc((x.direction||x.best_dir||x.dir||'').toUpperCase())}</td><td>${money(x.amount||x.fill_amount||x.fill_amt)}</td><td>${num(x.best_ev,4)}</td><td>${esc(x.status||'')}</td><td>${esc(x.reason||'')}</td></tr>`,7);
}
async function loadLogs(){const q=encodeURIComponent($('log-q')?.value||''),level=encodeURIComponent($('log-level')?.value||'all');const lg=await api(`/api/logs?n=220&q=${q}&level=${level}`);$('logbox').textContent=(lg.items||[]).map(x=>`[${x.source}] ${x.text}`).join('\n')||'暂无日志'}
async function loadAll(){try{await Promise.all([loadLive(),loadReal(),loadShadow(),loadLogs()])}catch(e){$('health').textContent='异常 '+e;$('health').className='pill bad'}}
function pageFromPath(){const p=location.pathname.replace('/','')||'live';return ['real','shadow','logs'].includes(p)?p:'live'}
function setPage(p){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.page===p));document.querySelectorAll('.sec').forEach(s=>s.classList.toggle('active',s.id===p));history.replaceState(null,'',p==='live'?'/':'/'+p)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setPage(b.dataset.page));
document.querySelectorAll('#real-filters input,#real-filters select').forEach(el=>{el.addEventListener('change',loadReal);el.addEventListener('input',()=>{clearTimeout(window.__realFilterTimer);window.__realFilterTimer=setTimeout(loadReal,500)})});
document.querySelectorAll('#shadow-filters input,#shadow-filters select').forEach(el=>{el.addEventListener('change',loadShadow);el.addEventListener('input',()=>{clearTimeout(window.__shadowFilterTimer);window.__shadowFilterTimer=setTimeout(loadShadow,500)})});
setPage(pageFromPath());loadAll();setInterval(tickTime,1000);setInterval(loadLive,1000);setInterval(()=>{const p=pageFromPath(); if(p==='real')loadReal(); else if(p==='shadow')loadShadow(); else if(p==='logs')loadLogs();},5000);
